### PR TITLE
Update/consolidate installation issue template as form

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
### Summary

This PR eliminates the redundant installation issue templates, and consolidates them into one snazzy (yaml-based) form. There is now a checkbox that determines whether a package should be installed on WCOSS2. If it is checked, then we will create an issue in a project that lives under NOAA-EMC.

### Testing

Tested in personal fork.

### Applications affected

n/a

### Systems affected

n/a

### Dependencies

none

### Issue(s) addressed

Addresses #830

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
Thanks very much for this!

**Comment by climbfuji** [comment]
@edwardhartnett @Hang-Lei-NOAA Can you please review this PR? Thanks!

**Review by Hang-Lei-NOAA — APPROVED** [review]
This is a very good start.

**Comment by climbfuji** [comment]
@edwardhartnett mentioned in a separate discussion that this template looks excellent, therefore assuming we have his approval.

**Pull request merged**
