### PR TITLE
Add module vars

### PR DESCRIPTION
**Pull request by kgerheiser**
* NCEPLIBS module variables that are used by some applications.
* Update MAPL prefix for ESMF 8.3.0

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Do we need to do the same for the `tcl` module section?

Note, I thought that in a later PR (post release 1), we could use an include statement for both `lmod` and `tcl` for the common pieces?

**Comment by kgerheiser** [comment]
Ugh, do I have to repeat the same text for that?

**Comment by climbfuji** [comment]
> Ugh, do I have to repeat the same text for that?

Unfortunately, yes - but maybe not 100%, but almost. Gotta be careful, because some of the module labeling rules are different for `tcl`. That's why I'd like to have the common sections in a modules_common.yaml that get included in both the `lmod` and `tcl` section. If you like to do this in this PR, might as well do it and fix the open issue for that (#50).

**Comment by kgerheiser** [comment]
I duplicated the vars. Let me split this up if I'm going to factor out the common vars. It'll take a little Spack/Python yaml work for a `modules_common.yaml`.

**Review by climbfuji — COMMENTED** [review]
Thanks! Should we merge this in the meanwhile and add your logic in a follow-up PR, or should we wait update this PR?

**Comment by kgerheiser** [comment]
I would rather merge this, and add it in a follow-up PR

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
