### PR TITLE
Add cylc-flow, cylc-rose, cylc-uiserver, bump Python to 3.10.13

### LINKED ISSUE #887: [INSTALL]: Python 3.10.12+
### Package name

Python

### Package version/tag

3.10.12 or newer

### Build options

Current

### Installation timeframe

With the next release, though it would be good to have a test environment with metplus/3.1.1 to verify it works before installing everywhere.

### Other information

There is an import bug in Python 3.10.8 that appears to be resolved with 3.10.12 (see https://github.com/python/cpython/issues/88227) that affects METplus version 3.1.1 (see https://github.com/NOAA-EMC/global-workflow/issues/2091).

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

_No response_

### WCOSS2: Installation and testing

_No response_

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

### WCOSS2: Additional comments

_No response_

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

Necessary config and spack submodule pointer updates for adding `cylc-flow`, `cylc-rose`, `cylc-uiserver`.

Along with this, bump Python to version 3.10.13 (see https://github.com/JCSDA/spack/pull/377 for some background information on why we can use newer Python versions than 3.9 with `cylc` in `spack-stack`. This Python version is also compatible with what is requested in #887.

I removed several legacy versions for Python packages as part of this process, since I ran into problems with duplicate packages.

### Testing

- Tested locally on @climbfuji's macOS: All three packages build, I could run a basic cylc suite and create a graph as `png`. I could also launch the cylc jupyterhub server and dashboard.
- I repeated this on AWS ParallelCluster with Intel
- CI tests pass
- **Todo** @BenjaminRuston Is going to test the cylc installation for Intel on AWS ParallelCluster with his codes
- @climbfuji ran the following jedi/skylab tests to make sure the updated versions of Python packages are ok
    - [x] `qg-fullDA.yaml`
    - [x] `l95-fullDA.yaml`
- **Todo?** Does EPIC or EMC want to run tests with this code for UFS SRW App / UFS Weather Model / ... ? @ulmononian @AlexanderRichert-NOAA @DavidHuber-NOAA ?

**Note** When we install this on the HPCs, we will need to add `sed` as an external package, and possibly do the same in the instructions for generating new site configs for Linux (probably not macOS, because the spack package that asks for sed will want gnu-sed and not macOS-sed). See https://github.com/JCSDA/spack-stack/issues/904

### Applications affected

n/a

### Systems affected

All systems that use the `unified-dev` or `skylab-dev` templates.

### Dependencies

- [x] waiting on https://github.com/JCSDA/spack/pull/377

### Issue(s) addressed

Working towards https://github.com/JCSDA/spack-stack/issues/242
Resolves #887 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]
Approved (don't forget .gitmodules)

**Review by srherbener — APPROVED** [review]

**Review by DavidHuber-NOAA — APPROVED** [review]

**Comment by DavidHuber-NOAA** [comment]
Thanks for the Python version bump!

**Review by ulmononian — APPROVED** [review]

**Review by BenjaminRuston — APPROVED** [review]
was able to use cylc8 for basic think,, register a suite and `play` it (not `run`) and also viewed status using both `workflow-state` and `tui`

the output of `tui` is shown below:
image

**Comment by climbfuji** [comment]
> was able to use cylc8 for basic think,, register a suite and `play` it (not `run`) and also viewed status using both `workflow-state` and `tui`
> 
> the output of `tui` is shown below: image

Brilliant, thanks very much for testing @BenjaminRuston !

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Concretizes fine on acorn & orion, tested a couple python-based packages and all looks good. Didn't test met/metplus.

**Pull request merged**
