### PR TITLE
Add ncdiag/1.1.1 to the stack

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
### Summary

Update the spack hash to include the recently added ncdiag (version 1.1.1) library and include the library in the development UFS SRW template.

### Testing

Built a test environment on S4.

### Applications affected

GSI

### Systems affected

All

### Dependencies

Already merged: noaa-emc/gsi-ncdiag#4 and jcsda/spack#285.
### Issue(s) addressed

#651

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by ulmononian — COMMENTED** [review]
thanks for making this update, @DavidHuber-NOAA. 

i may be missing something, but from my end, it does not seem like the spack hash has been updated in this pr. i only see updates to the gsi-ncdiag version in configs/common/packages.yaml and configs/templates/ufs-srw-dev/spack.yaml.

**Comment by DavidHuber-NOAA** [comment]
@ulmononian Correct.  The stack was actually updated yesterday in develop, which covers the ncdiag upgraded version.  This PR is probably not critical at this point due to that update.

**Comment by ulmononian** [comment]
> @ulmononian Correct. The stack was actually updated yesterday in develop, which covers the ncdiag upgraded version. This PR is probably not critical at this point due to that update.

total oversight on my part -- thanks for clearing this up for me. i see now that your changes were merged in one commit before the current spack hash.

**Review by ulmononian — APPROVED** [review]
looks good!

**Comment by DavidHuber-NOAA** [comment]
The ufs-srw-dev environment does not build on Hera.  In particular, met version 10.1 fails because it cannot find automake-1.16 when building with Intel.  Is this a known issue?

**Comment by ulmononian** [comment]
> The ufs-srw-dev environment does not build on Hera. In particular, met version 10.1 fails because it cannot find automake-1.16 when building with Intel. Is this a known issue?

i have not encountered this on previous builds of the ufs-srw-dev environment on hera. in the hera site config (https://github.com/JCSDA/spack-stack/blob/develop/configs/sites/hera/packages.yaml), it points to external `automake/1.13.4`. sounds like some package version change caused it to concretize with a different automake.

two questions:
1. is it failing to fetch the source code for the automake version it has concretized with? if so, it's probably a hera firewall issue.
2. are you building the ufs-srw-dev env from that template's spack.yaml, or as part of the unified environment?

**Comment by AlexanderRichert-NOAA** [comment]
@DavidHuber-NOAA are you still have issues with building ufs-srw-env? The problem you described rings a bell, I think I ran into something similar recently, so I'm happy to take a look if it's still giving you trouble. It might just be that we need to avoid one or two external packages in the hera config.

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
The ufs-srw-dev issues on hera are independent of this PR. I approved it, will get merge once the tests pass again after the update from develop.

**Comment by DavidHuber-NOAA** [comment]
@ulmononian Sorry for the late reply.
1. No, it appears it concretized with the locally installed version, 1.13.4.  I created an environment (gsi).  Under envs/gsi/site/packages.yaml:
```
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
```

I don't see automake listed anywhere else except under the blacklists of configs/common/modules.yaml.

2. I'm building from the template's spack.yaml.

@AlexanderRichert-NOAA I am restarting my build process from the current develop branch and will report if the issue is still there.  If so, should I open a new issue?

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA I attempted reinstalling with --fail-fast, which caused an earlier failure in mapl during the cmake step when attempting to use an ecbuild declaration:

```
==> Installing mapl-2.22.0-r7eehymjb3fgiw2otrxy56u2mhjhvyo3
==> No binary for mapl-2.22.0-r7eehymjb3fgiw2otrxy56u2mhjhvyo3 found: installing from source
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure th
at your connection to this mirror is secure!
==> Fetching file:///scratch1/NCEPDEV/global/spack-stack/source-cache/_source-cache/archive/33/3356b8d29813431d272c5464e265f3fe3ce1ac7f49ae6d41da34fe4b82aa691a.tar.gz
==> Fetching file:///scratch1/NCEPDEV/global/spack-stack/source-cache/_source-cache/git/GEOS-ESM/ESMA_cmake.git/v3.21.0.tar.gz
==> Moving resource stage
        source: /scratch2/NAGAPE/epic/David.Huber/spack-stack/cache/build_stage/resource-esma_cmake-r7eehymjb3fgiw2otrxy56u2mhjhvyo3/spack-src/
        destination: /scratch2/NAGAPE/epic/David.Huber/spack-stack/cache/build_stage/spack-stage-mapl-2.22.0-r7eehymjb3fgiw2otrxy56u2mhjhvyo3/spack-src/spack-src
==> Ran patch() for mapl
==> mapl: Executing phase: 'cmake'
==> [2023-07-03-22:02:22.976030] '/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/cmake-3.23.1-xksr7js/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:
STRING=/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/mapl-2.22.0-r7eehym' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDU
RAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/g
si/install/intel/2021.5.0/mapl-2.22.0-r7eehym/lib;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/mapl-2.22.0-r7eehym/lib64;/scratch2/NAGAPE/epic/David.Huber/sp
ack-stack/envs/gsi/install/intel/2021.5.0/esmf-8.3.0b09-joibzbj/lib;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/netcdf-c-4.7.4-vkcljws/lib;/scratch2/NAGAPE/
epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/hdf5-1.10.6-43oxgiu/lib;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/zlib-1.2.11-rhgygrv/lib;/sc
ratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/netcdf-fortran-4.5.4-5cfrd5j/lib;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/para
llel-netcdf-1.12.2-vkgqiu6/lib;/scratch1/NCEPDEV/global/spack-stack/apps/miniconda/py39_4.12.0/lib;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/libaec-1.0.6-
mfbvaiu/lib64' '-DCMAKE_PREFIX_PATH:STRING=/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/parallel-netcdf-1.12.2-vkgqiu6;/scratch2/NAGAPE/epic/David.Huber/spac
k-stack/envs/gsi/install/intel/2021.5.0/gftl-shared-1.5.0-zmhetpl;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/gftl-1.10.0-n5slygb;/scratch2/NAGAPE/epic/Davi
d.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/esmf-8.3.0b09-joibzbj;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/netcdf-fortran-4.5.4-5cfrd5j;/scratch2
/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/netcdf-c-4.7.4-vkcljws;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/hdf5-1.10.6-43oxgiu;
/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/zlib-1.2.11-rhgygrv;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/libaec-1.0.6-m
fbvaiu;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/ecbuild-3.7.2-dzefpbh;/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/cmake
-3.23.1-xksr7js;/scratch1/NCEPDEV/global/spack-stack/apps/miniconda/py39_4.12.0;/apps/oneapi' '-DBUILD_WITH_FLAP:BOOL=OFF' '-DBUILD_WITH_PFLOGGER:BOOL=OFF' '-DBUILD_WITH_FARGPARSE:BOOL=OFF'
'-DBUILD_SHARED_MAPL:BOOL=OFF' '-DUSE_EXTDATA2G:BOOL=OFF' '-DUSE_F2PY:BOOL=OFF' '-DCMAKE_C_COMPILER=/apps/oneapi/mpi/2021.5.1/bin/mpiicc' '-DCMAKE_CXX_COMPILER=/apps/oneapi/mpi/2021.5.1/bin/
mpiicpc' '-DCMAKE_Fortran_COMPILER=/apps/oneapi/mpi/2021.5.1/bin/mpiifort' '-DCMAKE_MODULE_PATH:STRING=/scratch2/NAGAPE/epic/David.Huber/spack-stack/envs/gsi/install/intel/2021.5.0/esmf-8.3.
0b09-joibzbj/cmake' '/scratch2/NAGAPE/epic/David.Huber/spack-stack/cache/build_stage/spack-stage-mapl-2.22.0-r7eehymjb3fgiw2otrxy56u2mhjhvyo3/spack-src'
-- The Fortran compiler identification is Intel 2021.5.0.20211109
-- The CXX compiler identification is Intel 2021.5.0.20211109
-- The C compiler identification is Intel 2021.5.0.20211109
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /apps/oneapi/mpi/2021.5.1/bin/mpiifort - skipped
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /apps/oneapi/mpi/2021.5.1/bin/mpiicpc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /apps/oneapi/mpi/2021.5.1/bin/mpiicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Building MAPL as STATIC libraries
CMake Error at CMakeLists.txt:111 (ecbuild_declare_project):
  Unknown CMake command "ecbuild_declare_project".
```

**Comment by DavidHuber-NOAA** [comment]
Oh, I see my mistake.  I'm not loading the prerequisite libraries.  I will do that and try again.

**Comment by DavidHuber-NOAA** [comment]
Nope, that didn't work.  I am still seeing the same ecbuild cmake error for the mapl build.  I'll go ahead and open an issue.

**Pull request merged**
