### PR TITLE
release/1.4.0: Update site configs part 2, fix duplicate nco installations

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR contains documentation updates for a second batch of sites. It also contains updates to the Jet/S4/Orion site configs (and the documentation) to fix duplicate `nco` packages being built with `gcc`.

## Definition of Done

Updates in this PR reflect the successful installations on these systems

### Issue(s) addressed

Working towards #599

## Dependencies

none

### CODE REVIEW

**Review by ulmononian — APPROVED** [review]
thanks for fixing the greatest bison drama since the yellowstone bison drama two days ago.

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
I am running a little demo this afternoon on git, submodules, forks etc - need this PR open. Will merge when done, thanks for the quick reviews

**Comment by ulmononian** [comment]
> I am running a little demo this afternoon on git, submodules, forks etc - need this PR open. Will merge when done, thanks for the quick reviews

is there going to be a recording of this git clinic?

**Comment by climbfuji** [comment]
No, it’s something specific to JCSDA, wouldn’t be that useful for others

**Pull request merged**
