### PR TITLE
Simplify spack stack extension, update documentation, remove unused `configs/sites/redhat`

### LINKED ISSUE #195: Simplify `spack stack` extension for first release
The full set of options for the `spack stack` extension is:
```
spack stack [create|setup-meta-modules]

spack stack create [env|container]

# This is way too complicated and confusing!
spack stack create env [--template TEMPLATE] [--specs [SPECS [SPECS ...]]] [--name NAME] [--dir DIR] [--overwrite] [--packages PACKAGES] [--site SITE] [--prefix PREFIX] [--envs-file ENVS_FILE]

# This is not as bad, but still too complicated and confusing!
spack stack create container [--template TEMPLATE] [--specs [SPECS [SPECS ...]]] [--name NAME] [--dir DIR] [--overwrite] [--packages PACKAGES] container
```

Suggestions/questions for `env` and `container`:
1. Get rid of `--specs` - tell user to use template `TEMPLATE` (default `empty`), and when using empty, add specs (can refer to section _Environments_ in the documentation - this section is still missing, but will be completed before the release).2. 

Suggestions/questions for `env`:
2. Get rid of `--envs-file`? if users want to create an environment from a complete envs file, they don't need the overhead of running `spack stack create env`, they can just create a directory and copy the envs file there. It's also something that likely only advanced users want to do, therefore don't need to document? Can add some documentation if we think it is worth it.
3. Why do we need `--prefix` and `--dir`? Should we just always place the enviroment in `envs/name` and let the user overwrite only `prefix`?

Suggestions/questions for `container`:
4. In the help for the command, replace the container option with `container-option` or something like that, because we have `spack stack create container ... container` and that is confusing.
5. Same as for `env`, should we get rid of `--dir`?

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

- Update documentation and spack submodule pointer for changes in https://github.com/NOAA-EMC/spack/pull/96
- This shortens the name of the command `spack stack create container` to `spack stack create ctr` (which is the official abbreviation for container), leaving the full name for the positional argument `container`
- Remove unused `configs/sites/redhat`

## Dependencies

- waiting on https://github.com/NOAA-EMC/spack/pull/96

## Issues

- fixes https://github.com/NOAA-EMC/spack-stack/issues/195

### CODE REVIEW

**Comment by climbfuji** [comment]
Turns out that not being able to see the log is a bug in my safari :-( Checking in chrome now.

**Comment by climbfuji** [comment]
Ok, this is the problem:
```
==> Warning: Missing a source id for jedi-tools-env@1.0.0
==> Error: Cannot find valid provider for virtual mpi
```

**Comment by climbfuji** [comment]
My stupid mistake, trying again.

**Comment by kgerheiser** [comment]
Tests are passing except for the disabled GCC-9 Linux.

**Comment by climbfuji** [comment]
> Tests are passing except for the disabled GCC-9 Linux.

Nice! I'll turn the forgotten one on and clean up the code! Hi from Lathrop State Park :-)

**Comment by climbfuji** [comment]
@kgerheiser Opening this up for review, will also kick off the full CI build tests once the concretize tests are complete. Will add corresponding updates to the documentation on Sunday evening.

**Comment by climbfuji** [comment]
One of the full build tests is failing with
```
Setting environment variable SPACK_STACK_DIR to /Users/runner/work/spack-stack/spack-stack
Sourcing spack environment /Users/runner/work/spack-stack/spack-stack/spack/share/spack/setup-env.sh
==> Error: Not found: jedi-ewok-env
==> Removing jedi-ewok-env from environment /Users/runner/work/spack-stack/spack-stack/envs/default
Error: Process completed with exit code 1.
```
This is weird, because it should ignore the error:
```
  # Remove specs that don't build under certain configurations.
  if [[ "gcc@9" == "intel"* ]]; then
    spack rm jedi-tools-env || true
  fi
  
  if [[ "$RUNNER_OS" == "macOS" && "gcc@9" == "gcc"* ]]; then
    spack rm jedi-ewok-env || true
  fi
```
Also, the ubuntu-intel tests didn' fail at this point. But, we only need this for the concretize steps at the moment (the full builds only build one spec at a time), so what I will do is wrap this block in a test for `concretize_only`.

**Comment by climbfuji** [comment]
@kgerheiser This is ready for review and merging and will be the last PR for spack-stack before creating the jcsda_emc_release_v1 branch and the spack-stack-1.0.0-rc1 release candidate.
- The associated spack submodule PR will need to be updated first, then the usual `.gitmodules` and submodule pointer update here
- The documentation for this PR can be seen here: https://spack-stack--196.org.readthedocs.build/en/196/index.html
- All CI tests (automatic ones and manual ones) except the known issue with "spack-mirror-create" are passing, see macos-llvm-clang-build #26 and up.

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
