### PR TITLE
Update Orion site config after Rocky9 transition (for develop)

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

All in the title. This is nearly the same as https://github.com/JCSDA/spack-stack/pull/1171, but for develop instead of release/1.7.0.

### Testing

Built the unified environment on Orion with Intel.

### Applications affected

n/a

### Systems affected

Orion

### Dependencies

n/a

### Issue(s) addressed

Working towards https://github.com/JCSDA/spack-stack/issues/981

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [ ] ~~All dependency PRs/issues have been resolved and this PR can be merged.~~

### CODE REVIEW

**Comment by climbfuji** [comment]
Tagging @ulmononian for EPIC, since @RatkoVasic-NOAA is on leave

**Comment by AlexanderRichert-NOAA** [comment]
I'm still not sure I understand mixing our own gcc 12 with the system one. Why not either take out the module load or use the executables from the module?

**Comment by climbfuji** [comment]
> I'm still not sure I understand mixing our own gcc 12 with the system one. Why not either take out the module load or use the executables from the module?

I am only using what @RatkoVasic-NOAA prepared. Ratko built gcc@12.2.0 in the role-epic space, and openmpi@4.1.6 with that compiler.

The instructions for Orion are:
```
   module purge
   module use /work/noaa/epic/role-epic/spack-stack/orion/modulefiles
```
(and `module load ecflow/5.8.4`, but we should really remove all of these since they aren't needed).

If you follow that, you get:
```
------------------------------------------------------------------------------------------ /work/noaa/epic/role-epic/spack-stack/orion/modulefiles -------------------------------------------------------------------------------------------
   ecflow/5.8.4    gcc/12.2.0 (D)    miniconda/3.9.7    mvapich2/2.3.7    mysql/8.0.31    openmpi/4.1.6 (D)
```

The problem was that the sysadmin's gcc installation (with modulefile with the same name ...) was broken when Ratko started.

**Comment by AlexanderRichert-NOAA** [comment]
Does openmpi need to be more recent than the 4.1.4 available through the system, or can we just use gcc and openmpi from the system modules?

**Comment by climbfuji** [comment]
Same story, openmpi was not functional (just like gcc) when Ratko built spack-stack. Not sure if the sysadmins fixed all of these by now.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Feel free to take this PR and switch the compiler and OpenMPI; one issue though is that the 1.7.0 spack-stack installs now use the gcc/12.2.0 modulefile that Ratko created; I am not sure if things break if we remove/rename that file (which we will have to in order to still be able to access the ecflow modulefile but use the gcc/12.2.0 module from the sysadmins; UNLESS we do a `module use --append` on Orion - but that would make this the only system, not a good idea either).

Either way, I don't think I have a lot of time to spend on Orion this and next week before I go on leave for three weeks.

**Comment by AlexanderRichert-NOAA** [comment]
I'm testing out system gcc and openmpi with 1.5.1, I'll see how things look and judge from there.

**Comment by ulmononian** [comment]
@AlexanderRichert-NOAA @climbfuji from what i understand, the sysadmin gcc/openmpi was not functional for various release versions of the stack, so ratko built them in the role epic space. using these, he was able to successfully install 1.7.0 and had moved onto 1.6.0. im not sure if anything has been fixed on the sysadmin side for gcc/openmpi. for develop it may be ok to change compiler/mpi, but should make sure to keep consistency for the release versions and what was installed.

**Comment by AlexanderRichert-NOAA** [comment]
See https://github.com/climbfuji/spack-stack/pull/8

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Please review again. Rendered documentation is here: https://spack-stack--1174.org.readthedocs.build/en/1174/PreConfiguredSites.html#msu-orion

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Pull request merged**
