### PR TITLE
Create hpc-dev environment

### PR DESCRIPTION
**Pull request by kgerheiser**
I think this should be our 'template' for deploying a single all-encompassing stack on HPC systems.

* It's self contained, with all non-implicit specs given in the spack.yaml

* You get multiple compilers at once without having to create separate environments. On all of our HPC systems we've been installing with Intel and GNU. A compiler can easily be added/removed.

* It excludes jedi-tools%intel

* It overrides the issue with #266 without having to manually edit anything

* The bundles get a version corresponding to the environment they are a part of.

I installed this on Hera successfully. If someone needs an extra package in this environment we simply add it to the list of packages until we retire this stack and move onto the next one.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
That looks great. Not entirely clear to me ... do you get separate environments for each of the packages listed?

**Comment by climbfuji** [comment]
> That looks great. Not entirely clear to me ... do you get separate environments for each of the packages listed?

Scrap that, you don't ... but I am surprised that the meta modules script worked out of the box?

**Comment by kgerheiser** [comment]
Yes, the meta-modules work out of the box if you have them both in `packages:all:compilers/providers`.

**Comment by climbfuji** [comment]
> Yes, the meta-modules work out of the box if you have them both in `packages:all:compilers/providers`.

Great! I wrote it that way but never tested it :-)

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
