### PR TITLE
Update Acorn config and include bufr@12.0.0 for 1.4.1

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Might as well include updates made post-1.4.0 installation to facilitate Acorn installation.

Also, update bufr default to 12.0.0.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
After this, we only need the bufr version update in spack-stack and then we are done with 1.4.1 I think.

**Comment by AlexanderRichert-NOAA** [comment]
Well, I accidentally pushed the bufr update to the same branch, so, I'm just gonna include it in this PR...

**Comment by climbfuji** [comment]
Can you also update it in https://github.com/JCSDA/spack-stack/blob/release/1.4.1/configs/containers/README.md (two places in that file) *after* the CI tests passed, please? No need to rerun CI again for README changes. Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
Yep no problem. Should 1.4.0 go to 1.4.1 as well?

**Comment by climbfuji** [comment]
> Yep no problem. Should 1.4.0 go to 1.4.1 as well?

Ah, yes please. I'll have to make more updates to the container yamls, but we can start installing from the release branch after this PR is merged. I usually create the tags post-install, one never knows what issues pop up during the install on various HPCs that need changes in their configs.

**Pull request merged**
