### PR TITLE
Add NRL as partner

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

Adding NRL as partner. I've also eliminated one redundant place where the maintainer names are specified, now down to two places.

### Testing

n/a

### Applications affected

n/a

### Systems affected

n/a

### Dependencies

n/a

### Issue(s) addressed

n/a

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] ~~These changes have been tested on the affected systems and applications.~~
- [ ] ~~All dependency PRs/issues have been resolved and this PR can be merged.~~

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
Ed's out this week but I'll run this by EIB in case there are any questions etc.

**Comment by climbfuji** [comment]
Sounds good @AlexanderRichert-NOAA. Rahul and Maoyi have been in discussions with NRL several weeks ago, but let me know if there are additional questions, please.

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by AlexanderRichert-NOAA** [comment]
One question I have- How much is the unified stack likely to need to change in terms of new packages, etc.?

**Comment by climbfuji** [comment]
Not much if any - we already have all or almost all packages in unified-env. And, beyond that, because JCSDA needs to run JEDI-NEPTUNE, any additional packages needed by NRL would come in via JCSDA otherwise.

**Review by AlexanderRichert-NOAA — APPROVED** [review]
No objections from EMC.

**Comment by climbfuji** [comment]
Thank you!

**Pull request merged**
