### PR TITLE
Spack configuration for UFS_UTILS.

### PR DESCRIPTION
**Pull request by HenryRWinterbottom**
## Description

This adds a configuration to build the software stack for the [UFS_UTILS](https://github.com/ufs-community/UFS_UTILS).

## Issue(s) addressed

This PR resolves issue #644. 

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
I am ok doing it this way, another way would be to update the https://github.com/JCSDA/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py and add any missing packages (but no version numbers) there, provided that the default versions in `configs/common/packages.yaml` work. This has the advantage that we can add `ufs-utils-env` to `unified-dev` so that we know that any unified environment we build supports ufs-utils.

**Comment by HenryRWinterbottom** [comment]
> I am ok doing it this way, another way would be to update the https://github.com/JCSDA/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py and add any missing packages (but no version numbers) there, provided that the default versions in `configs/common/packages.yaml` work. This has the advantage that we can add `ufs-utils-env` to `unified-dev` so that we know that any unified environment we build supports ufs-utils.

@climbfuji Thank you for the information! I'd be happy to use your suggested approach. I just wasn't aware of that preference until now.

If it is OK with your timelines, I will take a stab at it next week.

**Comment by climbfuji** [comment]
> > I am ok doing it this way, another way would be to update the https://github.com/JCSDA/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py and add any missing packages (but no version numbers) there, provided that the default versions in `configs/common/packages.yaml` work. This has the advantage that we can add `ufs-utils-env` to `unified-dev` so that we know that any unified environment we build supports ufs-utils.
> 
> @climbfuji Thank you for the information! I'd be happy to use your suggested approach. I just wasn't aware of that preference until now.
> 
> If it is OK with your timelines, I will take a stab at it next week.

No rush. if you want it to be part of the next release, you have about 2 months ;-)

**Comment by HenryRWinterbottom** [comment]
HA! Sounds good! But, we all know how quickly two months can come and go...

**Comment by ulmononian** [comment]
i would second @climbfuji's suggestion, but hey it can also be nice to have both options!

**Comment by climbfuji** [comment]
I would also like to note that using the last spack-stack release 1.4.0, I was able to compile ufs-utils on AWS Parallel Cluster from the unified-env (unified-dev template). It currently doesn't have the `ufs-utils-env` meta package enabled, but all the packages were there (I had to just load the modules manually). So maybe `ufs-utils-env` is already functional and can be used as is in your new template, and for us it's just a case of enabling `ufs-utils-env` in the unified-dev` template.

**Comment by HenryRWinterbottom** [comment]
@climbfuji @ulmononian I am happy to do whatever you think it is best. I am not interested in messing up JCSDA plans. I just needed it for development at the moment. If it is useful for you to use what's in the PR or me pursuing how you suggested, I am happy to do so. If you have something that exists (or will) I am happy to use it as well. I won't be offended. ;-)

Thanks for the feedback guys. This taught me something new about how the spack-stack capabilities are being used. It will certainly be useful for me moving forward.

**Comment by climbfuji** [comment]
It's still going to be useful to have a ufs-utils-env for folks that don't care about the other packages. But maybe it just needs one line in the specs (`- ufs-utils-env`) and, if certain versions are required, those can be requested above in a `packages` section. Let me know if this is not clear and I can help. Thanks!

**Comment by HenryRWinterbottom** [comment]
> It's still going to be useful to have a ufs-utils-env for folks that don't care about the other packages. But maybe it just needs one line in the specs (`- ufs-utils-env`) and, if certain versions are required, those can be requested above in a `packages` section. Let me know if this is not clear and I can help. Thanks!

@climbfuji Thank you for the feedback. I would like to try and configure this myself using your explanations above. It will provide me an opportunity to learn something new. If it's OK, maybe I just try to learn through this PR? Once it is working as it should we could just move the `ufs-utils-env` into the release as I think you are suggesting above?

Thoughts?

**Comment by climbfuji** [comment]
Yes, sounds good!

**Comment by HenryRWinterbottom** [comment]
@climbfuji OK, thank you. I have a few things in the global-workflow that I need to address ASAP -- from last week's conversation, about 2-months remain before the next release, correct? If so, I should be able to get to this by then (hopefully :-)).

**Pull request closed without merging**
