### PR TITLE
Restructure sites table for readability

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
### Summary
This PR restructures the sites table in PreConfiguredSites.rst to, hopefully, make it more readable. Specifically:
 - Organization, system name, and compilers are separate columns; I find it much easier to find a specific site by name this way.
 - Platform are now separated by HPC and cloud. This makes it easy to point someone to the docs when they ask "what cloud platforms do we support?"
 - I renamed a few things, namely, "NAVY"->"U.S. Navy", "GNU"->"GCC", "AMD clang/flang"->"AOCC", U of Wisconsin, and Parallel Works.

### Testing
Tested on personal machine (sphinx 1.7.6).

### Applications affected

n/a

### Systems affected

n/a

### Dependencies

none

### Issue(s) addressed

none

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications.
- [ ] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
This all looks good, but wondering where the footnote for the label `^**` went. Also, do you want to split up RDHPCs cloud into three sections (AWS, Azure, Gcloud) or keep them together (I don't care really, just asking).

**Comment by AlexanderRichert-NOAA** [comment]
Are those likely to have different paths at some point? If the other columns are all the same then I think it's fine to have them in one place.

I'll probably add "(Parallel Works)" to "RDHPCS Cloud" just to clarify since I've never actually heard it referred to as "RDHPCS Cloud" before today...

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji looks like the '^**' got added in https://github.com/JCSDA/spack-stack/commit/beeb5b39ece362930201d8f2d6502f27681427d6 but never had an actual footnote.

**Comment by climbfuji** [comment]
> @climbfuji looks like the '^**' got added in [beeb5b3](https://github.com/JCSDA/spack-stack/commit/beeb5b39ece362930201d8f2d6502f27681427d6) but never had an actual footnote.

Then we should probably just remove them, my bad.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
