### PR TITLE
Change py-bufr to bufr with +python variant

### PR DESCRIPTION
**Pull request by kgerheiser**
Related to https://github.com/NOAA-EMC/spack/pull/10

### CODE REVIEW

**Comment by climbfuji** [comment]
The problem I had was that it didn't want to find pip when the name was "bufr". But maybe the change to use "+python" does the same trick that the name "py-xyz" does. I used "enable_python" because that's how it was called in the nceplibs-bufr `CMakeLists.txt`. Using `python` is much better anyway.

**Comment by kgerheiser** [comment]
Hmm, I see the error. Other (non-Python) packages (fenics, cmor, mxnet) do the same thing, so it should be possible.

**Comment by kgerheiser** [comment]
Got it to work, just had to add `depends_on('py-pip')`

**Comment by kgerheiser** [comment]
@climbfuji can we merge this?

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
Yes! Sorry, I lost track of this one.

**Pull request merged**
