### PR TITLE
Allow show_duplicate_packages.py to ignore dup's from different compilers

### LINKED ISSUE #724: show_duplicates utility not working correctly when multiple compilers are used
**Describe the bug**
The util/show_duplicates.py utility doesn't work correctly if multiple compilers are used on a system for one environment, e.g. through the use of compiler matrices in spack.yaml. It reports duplicates because it doesn't know that %intel and %gcc are different things, for example.

A workaround is to use something like this:
```
> cat log.concretize.unified-env.001 | grep '%intel' | util/show_duplicate_packages.py -d
```

**To Reproduce**
Run `util/show_duplicate_packages.py` on a system with multiple compilers for unified-env

**Expected behavior**
Now false duplicates reported

**System:**
Discovered on Hercules, but applies on all systems with two or more compilers

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
### Summary

This PR adds an option to show_duplicate_packages.py that allows it to ignore duplicates that come from different compilers.

### Testing

Tested by hand; updated util_tests.sh (used in CI)

### Applications affected

n/a

### Systems affected

CI

### Dependencies

none

### Issue(s) addressed

Fixes #724

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Is there a reason why you don't want to make this behavior (ignore duplicates from different compilers) the default or the only option?

**Comment by AlexanderRichert-NOAA** [comment]
I can go either way on whether it's the default, so say the word and I'm happy to change it. Initially I figured users would grep as needed, but I'd like to leave the option to use the current behavior 1) because some (meta)packages, namely jedi-tools, should only be built with one or another compiler and we would want to catch it if they weren't, and 2) I wanted to leave room for more exotic situations where, say, an intel-based package depended on a gcc-based package and we would not want to gcc-based dependency to get duplicated.

**Comment by climbfuji** [comment]
> I can go either way on whether it's the default, so say the word and I'm happy to change it. Initially I figured users would grep as needed, but I'd like to leave the option to use the current behavior 1) because some (meta)packages, namely jedi-tools, should only be built with one or another compiler and we would want to catch it if they weren't, and 2) I wanted to leave room for more exotic situations where, say, an intel-based package depended on a gcc-based package and we would not want to gcc-based dependency to get duplicated.

Good points! Let's leave it as is then, we just need to update the documentation (either in this PR or a follow-up PR), it appears in several places:
```
> grep -Rie show_dupl doc
doc/source/NewSiteConfigs.rst:It is recommended to save the output of concretize in a log file and inspect that log file using the :ref:`show_duplicate_packages.py <Duplicate_Checker>` utility.
doc/source/NewSiteConfigs.rst:   util/show_duplicate_packages.py -d log.concretize
doc/source/NewSiteConfigs.rst:It is recommended to save the output of concretize in a log file and inspect that log file using the :ref:`show_duplicate_packages.py <Duplicate_Checker>` utility.
doc/source/NewSiteConfigs.rst:   util/show_duplicate_packages.py -d log.concretize
doc/source/Utilities.rst:show_duplicate_packages.py
doc/source/Utilities.rst:The utility located at util/show_duplicate_packages.py parses the output of ``spack concretize`` and detects duplicates. Usage is as follows:
doc/source/Utilities.rst:   spack concretize | ${SPACK_STACK_DIR}/util/show_duplicate_packages.py
doc/source/Utilities.rst:   ${SPACK_STACK_DIR}/util/show_duplicate_packages.py log.concretize
doc/source/PreConfiguredSites.rst:   spack concretize | ${SPACK_STACK_DIR}/util/show_duplicate_packages.py -d log.concretize
```

**Review by climbfuji — APPROVED** [review]
I pushed the change you made for the macos new site config for Linux as well. I checked the rendered documentation and it looks good! Thanks very much.

**Comment by climbfuji** [comment]
I will merge this after https://github.com/JCSDA/spack-stack/pull/722 (so that I don't have to rerun the CI tests there; this PR here is already out of date and will require CI reruns anyway).

**Pull request merged**
