### PR TITLE
Fix table column widths & parallelworks section.

### LINKED ISSUE #677: readthedocs rendering of tier 1 spack-stack install table not working
**Describe the bug**
See https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html - something must have gone wrong with the rendering of the table in the latest PR https://github.com/JCSDA/spack-stack/pull/675

**Additional context**
Columns need to be the same width for tables to be rendered correctly

### PR DESCRIPTION
**Pull request by ulmononian**
### Summary

@ulmononian broke the table in the pre-configured sites section of the docs w/ the c5/hercules updates.

this fixes that and some minor formatting issues in the parallelworks section.

### Testing

none

### Applications affected

none

### Systems affected

none

### Dependencies

none

### Issue(s) addressed

Fixes #677 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
Thanks, looks good!

https://spack-stack--679.org.readthedocs.build/en/679/PreConfiguredSites.html#officially-supported-spack-stack-1-4-1-installations-tier-1

**Comment by ulmononian** [comment]
dang. this parallel works maintainers section ref is still not working (there was an extra space before that i removed), but it still does not render correctly:

https://github.com/ulmononian/spack-stack/blob/9e5c3b8ab4e9454e0200e69dc2b7db7f9be9541a/doc/source/PreConfiguredSites.rst?plain=1#L391

Screen Shot 2023-07-19 at 11 56 05 AM

see any issue?

**Comment by climbfuji** [comment]
@ulmononian fixed

**Comment by climbfuji** [comment]
See https://github.com/JCSDA/spack-stack/pull/679/commits/ee5310fbcbabf81377fd14583c975674d3ceaed1

**Comment by ulmononian** [comment]
> @ulmononian fixed

thanks dom. i deleted the problematic space, but then added "NOAA" thinking i knew what i was doing. clearly i did not.

**Pull request merged**
