### PR TITLE
Upgrade bufr to 12.1.0, build met/metplus 9.1.3/3.1.1 in the unified environment

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
### Summary

This upgrades BUFR to 12.1.0 and allows MET and METplus v9.1.3 and v3.1.1 to be installed in the unified environment without sacrificing macOS support.

### Testing

Concretized on Hera, building a test environment in `/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_bufr_12.1/envs/unified_b121_m913`.

### Applications affected

Global workflow, GSI, JEDI, UFS-SRW-App, GDASApp

### Systems affected

All

### Dependencies

https://github.com/JCSDA/spack-stack/pull/1217

### Issue(s) addressed

#1251 
#1060 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
        Upgrading BUFR to 12.1.0 and MET/METplus to 3.1.1/9.1.3 allows for a unified environment for all apps
- [ ] These changes have been tested on the affected systems and applications.
- [ ] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
@climbfuji ~Since I am bumping the spack version,~ Do I need to remove the build cache?  Wondering if that is why the `ubuntu-ci` test failed.

EDIT: N/M the spack version bump.  I see now that Ratko bumped it yesterday.

**Comment by climbfuji** [comment]
@DavidHuber-NOAA We are getting CI build errors, duplicate packages:
```
7pgknjr  cairo@1.16.0%intel@2021.10.0~X~fc~ft~gobject~pdf+pic~png+shared~svg  build_system=autotools  patches=7097196,7c4da77  arch=linux-ubuntu22.04-zen2
xkuwaaw  cairo@1.16.0%intel@2021.10.0~X~fc~ft~gobject~pdf+pic~png+shared~svg  build_system=autotools  patches=7097196,7c4da77  arch=linux-ubuntu22.04-zen2
fttndva  glib@2.78.3%intel@2021.10.0~libmount~strip  build_system=meson  buildtype=release  default_library=shared  tracing=none  arch=linux-ubuntu22.04-zen2
Duplicates found!
iojokmf  glib@2.78.3%intel@2021.10.0~libmount~strip  build_system=meson  buildtype=release  default_library=shared  tracing=none  arch=linux-ubuntu22.04-zen2
qqs24fu  meson@1.3.2%intel@2021.10.0  build_system=python_pip  patches=0f0b1bd  arch=linux-ubuntu22.04-zen2
farkcw7  meson@0.61.2%intel@2021.10.0  build_system=python_pip  patches=aa6c50d  arch=linux-ubuntu22.04-zen2
ylwzmg2  met@11.1.1%intel@2021.10.0+graphics+grib2+lidar2nc+modis+openmp+python  build_system=autotools  arch=linux-ubuntu22.04-zen2
koqzmqh  met@9.1.3%intel@2021.10.0+graphics+grib2+lidar2nc+modis+openmp+python  build_system=autotools  arch=linux-ubuntu22.04-zen2
6eorjnf  metplus@3.1.1%intel@2021.10.0~cycloneplotter~makeplots~plotdataplane~series_analysis~tcmpr_plotter  build_system=generic  arch=linux-ubuntu22.04-zen2
gcgxany  metplus@5.1.0%intel@2021.10.0~cycloneplotter~makeplots~plotdataplane~series_analysis~tcmpr_plotter  build_system=generic  arch=linux-ubuntu22.04-zen2
```

**Comment by climbfuji** [comment]
No need to remove the build cache. You are getting duplicate packages. I wonder if we should spend all this effort or keep the separate gsi env for one or two more releases. Once we move to the Intel oneAPI compilers, met@9 is for the history books.

**Comment by DavidHuber-NOAA** [comment]
Alright, I'll go with the gsi-env then.  I thought I had an easy shot...

**Comment by climbfuji** [comment]
> Alright, I'll go with the gsi-env then. I thought I had an easy shot...

I agree, it would have been nice to have. 

We still need the bufr updates, though - do you want to do this, or should I?

**Comment by DavidHuber-NOAA** [comment]
Yes, I will do it.

**Comment by climbfuji** [comment]
> Yes, I will do it.

Merci!

**Pull request closed without merging**
