### PR TITLE
Add WGRIB variable to grib-util module

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
### Summary

This PR adds a variable WGRIB for the wgrib executable in the grib-util module.

### Testing

Tested on personal machine

### Applications affected

UPP, Global Workflow, EMC verif

### Systems affected

all

### Dependencies

none

### Issue(s) addressed

#1097

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications.
- [ ] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Ready for review?

**Comment by climbfuji** [comment]
This needs to be back-ported to 1.5.1 and 1.6.0 on all systems (module generation only)

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA This PR still says "testing in progress" - has this been done? @DavidHuber-NOAA mentioned in the last meeting that this needs to be rolled into 1.5.1 and 1.6.0. Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
Yes this is good to go, let me know if you want me to do some of the backporting.

**Comment by climbfuji** [comment]
I think we need the usual list of platforms and then work with @RatkoVasic-NOAA and @srherbener to make the one-line change (manually I suggest) in the env common config for 1.5.1 and 1.6.0?

**Pull request merged**
