### PR TITLE
Add R2D2 mysql dependencies and complete site config updates for unified environment

### LINKED ISSUE #383: Add new R2D2 thirdparty dependencies for mysql backend
## Description

JCSDA's R2D2 will migrate to a mysql database backend for storing metadata (not the actual data). This idea was presented to NOAA-EMC several weeks ago and was received positively. Note: this is *not* an approval for the software to go onto wcoss2 yet, and not a commitment to using the system.

The required 3rd-party packages are:
- mysql (community server): this might be available as an external on all/most systems already

**In particular, test and install those dependencies on AWS parallel cluster first.**

## What applications will be using this package or library
JCSDA and possibly partner agencies

## Is there already a package or library in spack-stack that provides this, or related, functionality?
n/a

## Additional context

**Will This Package be Needed in a NOAA Operational Application?**
If yes, the WCOSS System Software Checklist must also be completed.

**WCOSS System Software Request Checklist**

**TO BE FILLED IN**

General questions:

Supervisor or sponsor of the requester - **MISSING**

Software name and version, specific URL to the software - **MISSING**

Software type - New or Upgrade existing? - **MISSING**

Justification ( List NPS models using the software) - **MISSING**

Completion Time requested - **MISSING**

Software License including all Dependency Software Licenses - **MISSING**

Support contact(s) who must have a WCOSS account - **MISSING**

Dependency Software list - **MISSING**

Installation instructions - **MISSING**

Test and verification instructions - **MISSING**

Technical Review Checklist for open source software - Review the source code to answer the following questions

Licenses for the requested software and its dependencies - **MISSING**

Licenses -  confirm the software Licenses are acceptable - **MISSING**

Maturity - **MISSING**

Acceptable - Stable, production, or equivalent

Self-contained - **MISSING**

No external http, https,  ftp, or other URI exists except that in comments

No binary files in the package unless they are in the approved list

No publicly disclosed cybersecurity vulnerabilities and exposures 

Searching https://cve.mitre.org/cve/

Security High Level Checklists 

Is it prohibited by DHS/DOC/NOAA/NWS

Is it provided by a trusted source? Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat). 

Is software support offered (is it being updated and patched). 

If maintained by a private entity, does the entity operate in a foreign country, especially a prohibited foreign country (China, Russia, Iran, North Korea, etc.). 

Is there sufficient documentation to support maintenance 

Are there known vulnerabilities or weaknesses

Is there a need for privileged processes 

Are there software dependencies, are those dependencies approved or do they have any security concerns 

Are there any other concerns related to SA, SI, and SC control families

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Changes in this PR:
- Add dependencies for the upcoming R2D2 mysql backend implementation to various configs files,
- Update the submodule pointer for spack for the corresponding changes there
- Update CI scripts and documentation - avoid using the `padded_length` logic for now, too many issues. Instead, alwaus install in same location (env-name/env-dir)
- Add Ubuntu CI on AWS EC2, currently only with Intel on the AWS Parallelcluster head node of JCSDA
- Also update remaining site configs with changes required for the unified environment. The unified environment was introduced in https://github.com/NOAA-EMC/spack-stack/pull/454, PR https://github.com/NOAA-EMC/spack-stack/pull/480 updated some of the site configs, this PR adds the remaining site configurations for fully supported sites

With this PR and previous PRs, the following sites have updated compiler/package files for (a) the unified environment and (b) mysql. For sites marked with an asterisk `*`, the updated unified-environment was built successfully (manually).
- [x] Orion (Intel, GNU) `*`
- [x] S4 (Intel, GNU) `*`
- [x] Cheyenne (Intel, GNU) `*`
- [x] Casper (Intel)
- [x] Discover (Intel, GNU) `*`
- [x] Hera (Intel, GNU)
- [x] Jet (Intel, GNU)
- [x] AWS Parallelcluster (Intel) `*`
- [x] Narwhal (Intel, GNU)
- [x] Gaea
- [x] noaa-aws
- [x] noaa-azure
- [x] noaa-gcloud

The following sites are still missing, but we can do those in a follow-up PR (as long as before we roll out the spack-stack 1.3.0 release) -  but may want to consider moving this to a different "category" of support, as discussed in the last spack-stack meeting:

- [ ] Acorn
- [ ] Gaea c5
- [ ] emc-rhel (if building the unified-dev env)
- [ ] frontera
- [ ] comet

## Dependencies

- Waiting on https://github.com/NOAA-EMC/spack/pull/220

## Issues

Fixes #383

## Testing

- New Ubuntu and macOS CI tests passed for https://github.com/NOAA-EMC/spack-stack/pull/463/commits/45c55200373adc13951b1b361f55d9d658cd79d6
- Manual tests on platforms listed above and on Dom's macOS

### CODE REVIEW

**Review by srherbener — COMMENTED** [review]
In the documentation updates I'm not seeing updated instructions for the Mac regarding the need to install mysql with homebrew and to mark mysql as an external package. Should `brew install mysql` be added to the list showing the other `brew install` commands? Also add the `spack --not-buildable --scope system mysql` to the list of spack find commands?

Also, should we put in the tip about shutting off the auto updates of dependencies in the Mac instructions. Ie, add `export HOMEBREW_NO_AUTO_UPDATE=1` to your environment before running brew installs?

**Comment by climbfuji** [comment]
> In the documentation updates I'm not seeing updated instructions for the Mac regarding the need to install mysql with homebrew and to mark mysql as an external package. Should `brew install mysql` be added to the list showing the other `brew install` commands? Also add the `spack --not-buildable --scope system mysql` to the list of spack find commands?
> 
> Also, should we put in the tip about shutting off the auto updates of dependencies in the Mac instructions. Ie, add `export HOMEBREW_NO_AUTO_UPDATE=1` to your environment before running brew installs?

Indeed. Now the instructions are there. See https://github.com/NOAA-EMC/spack-stack/pull/463/commits/7952569edf80452d37a7907071de057f8fb8902a.

**Review by srherbener — APPROVED** [review]
Looks great. Thanks!

**Comment by srherbener** [comment]
I'm testing on my Mac now with the proper handling of the mysql package. I should have a result later this afternoon.

**Review by ericlingerfelt — APPROVED** [review]
Thanks, @climbfuji!

**Review by ulmononian — APPROVED** [review]
5stars. seems ready to roll!

**Pull request merged**
