### PR TITLE
No szip for WCOSS2 hdf5 & netcdf

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
No szip for WCOSS2 hdf5 & netcdf.

### CODE REVIEW

**Comment by climbfuji** [comment]
We don't need `szip` anywhere - can you instead remove it entirely (common / packages.yaml)?

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett @junwang-noaa is it correct to say we don't need szip support for hdf5/netcdf anywhere? I think we discussed this some time ago but I don't remember what the conclusion was.

**Comment by edwardhartnett** [comment]
Correct.

Both HDF5 and netCDF will build with or without szip (a.k.a. szlib). So unless we have some group that is demanding to use szip, or we have some szip-packed netCDF data we need to work with, we don't have to build it.

Both zlib and especially zstandard are better choices (faster, more compressive), so there's no reason for anyone to use this archaic compression.

**Comment by climbfuji** [comment]
Thanks Ed, that was my understanding as well.

**Comment by climbfuji** [comment]
Looks good! I'll take a look at the CI tests to check that it indeed built hdf5 and netcdf-c w/o szip support.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
