### PR TITLE
Update Parallel Works configs (AWS, Azure, Gcloud)

### LINKED ISSUE #569: wgrib2 build failure on azure
**Describe the bug**
wgrib2@2.0.8 (and 3.1.1) fails to build on paralleworks azure as a part of spack-stack/1.3.1 (intel).

**To Reproduce**

```

git clone --recursive -b release/1.3.1 https://github.com/NOAA-EMC/spack-stack.git
cd spack-stack

module unuse /opt/cray/craype/default/modulefiles
module unuse /opt/cray/modulefiles
export PATH="${PATH}:/contrib/spack-stack/apps/utils/bin"
module use /contrib/spack-stack/modulefiles/core
module load miniconda/3.9.12
module load mysql/8.0.31

source ./setup.sh

spack stack create env --site noaa-azure --template unified-dev --name unified-env
# comment out clang and gcc in envs/unified-env/spack.yaml
spack env activate envs/unified-env

spack concretize
spack install  

OR

spack install --add --verbose wgrib2@2.0.8%intel

```

Resultant error is:

```
==> wgrib2: Executing phase: 'build'
==> [2023-05-08-16:15:52.930840] 'make' '-j1'
make: *** No targets specified and no makefile found.  Stop.
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1'

1 error found in build log:
     19    ==> [2023-05-08-16:15:52.097171] FILTER FILE: makefile [replacing "^USE_IPOLATES=.*"]
     20    ==> [2023-05-08-16:15:52.291372] FILTER FILE: makefile [replacing "^DISABLE_TIMEZONE=.*"]
     21    ==> [2023-05-08-16:15:52.479990] FILTER FILE: makefile [replacing "^DISABLE_ALARM=.*"]
     22    ==> [2023-05-08-16:15:52.672032] FILTER FILE: makefile [replacing "^MAKE_FTN_API=.*"]
     23    ==> wgrib2: Executing phase: 'build'
     24    ==> [2023-05-08-16:15:52.930840] 'make' '-j1'
  >> 25    make: *** No targets specified and no makefile found.  Stop.
```

Oddly enough, `xcb-proto` fails for a similar reason: "no makefile found". I haven't seen this error before, and wgrib2 installs fine on gcp/aws.

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

This PR updates the Parallel Works spack-stack site configurations so that they are consistent with each other, with the directory layout described in the project charter, and provide everything needed for UFS and JEDI-Skylab applications.

Note that in order to function correctly, the following script needs to be run every time when a new cluster (head node) is provisioned (this can be run manually or automatically, configured on the Parallel Works resources page):
```
> cat /contrib/admin/basic_setup.sh
#!/bin/bash

chmod 777 /contrib
yum install -y qt5-qtbase-devel
yum install -y qt5-qtsvg-devel
yum install -y xorg-x11-xauth
yum install -y xorg-x11-apps
yum install -y perl-IPC-Cmd
yum install -y gettext-devel
```

**To be discussed**: Is this updated site config acceptable for EPIC, or do we need to different site configurations for EPIC and JCSDA? If we use one shared config, how do we make sure that we test updates and keep the configs in sync, given that we cannot mount the same filesystem under `/contrib`? Rsync the entire `/contrib/spack-stack` folder to somewhere else? Or build on a completely separate drive in the future that we can mount in both the EPIC and JCSDA accounts, for example as `/contrib-shared`?

**Note 1**: I updated the documentation (pre-configured sites, maintainers section) with my changes. I decided to put the basic setup instructions in a `README.md` (similar to what I did for `aws-pcluster` in the past), because there are a few more steps needed than on the HPCs. I think this works better for the cloud platforms.

**Note 2**: With this setup, I was able to build `wgrib2` on all platforms (addressing https://github.com/JCSDA/spack-stack/issues/569).

### Testing

- Install spack-stack develop as of August 17
    - [x] NOAA-AWS
    - [x] NOAA-Azure
    - [x] NOAA-Gcloud
- Build jedi-bundle develop as of August 21, run ctests. make sure all tests pass
    - [x] NOAA-AWS
    - [x] NOAA-Azure
    - [x] NOAA-Gcloud
- Build ufs-weather-model / ufs-srw-eapp (@ulmononian) and run basic tests (no failures)
    - [x] NOAA-AWS
    - [x] NOAA-Azure
    - [x] NOAA-Gcloud
- Build remaining Skylab components as of August 21 and run the following Skylab experiments: `qg-fullDA.yaml`, `l95-fullDA.yaml`, `skylab-atm-land-small.yaml`
    - [x] NOAA-AWS
    - [x] NOAA-Azure
    - [x] NOAA-Gcloud

See also https://github.com/JCSDA-internal/jedi-bundle/issues/31 if you have access.

### Applications affected

n/a

### Systems affected

NOAA Parallel Works platforms (AWS, Azure, Gcloud)

### Dependencies

n/a

### Issue(s) addressed

Resolves https://github.com/JCSDA-internal/jedi-bundle/issues/31
Resolves https://github.com/JCSDA/spack-stack/issues/569

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [ ] ~~All dependency PRs/issues have been resolved and this PR can be merged.~~

### CODE REVIEW

**Comment by mark-a-potts** [comment]
I'll test this out on our version of the cloud. I would like to keep our configurations consistent between JCSDA and EPIC. Keeping 6 separate machines all in sync is going to be challenging, though. 

Can we set up a binary cache that is accessible to all and then install using that cache to all other machines? I have had success rsyncing the spack-mirror binary cache across our 3 instances and then installing from that binary cache using the spack.lock file from the original install (otherwise, the hashes don't seem to match despite everything being almost identical).

**Comment by climbfuji** [comment]
> I'll test this out on our version of the cloud. I would like to keep our configurations consistent between JCSDA and EPIC. Keeping 6 separate machines all in sync is going to be challenging, though.
> 
> Can we set up a binary cache that is accessible to all and then install using that cache to all other machines? I have had success rsyncing the spack-mirror binary cache across our 3 instances and then installing from that binary cache using the spack.lock file from the original install (otherwise, the hashes don't seem to match despite everything being almost identical).

That's a good idea although I would advocate for populating the binary cache from all three platforms and then installing from it. We could use an S3 bucket, either a "traditional" one in AWS or one of NOAA's S3 adaptations (forgot the name).

**Comment by climbfuji** [comment]
@mark-a-potts @ulmononian Did you have a chance to test these proposed changes?

**Comment by ulmononian** [comment]
i ran:
```
chmod 777 /contrib
yum install -y qt5-qtbase-devel
yum install -y qt5-qtsvg-devel
yum install -y xorg-x11-xauth
yum install -y xorg-x11-apps
yum install -y perl-IPC-Cmd
yum install -y gettext-devel
```
after that, the initial prereq loading sequence did not work, as it failed to load ecflow due to not finding qt/5.5.12:
```
   module purge
   module unuse /opt/cray/craype/default/modulefiles
   module unuse /opt/cray/modulefiles
   module use /contrib/spack-stack/modulefiles
   module load cmake/3.27.2
   module load ecflow/5.8.4
   module load mysql/8.0.31
   module load git-lfs/2.4.1

   module load ecflow/5.8.4
   Lmod has detected the following error:  The following module(s) are unknown: "qt/5.15.2"

   Please check the spelling or version number. Also try "module spider ..."
   It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "qt/5.15.2"

  Also make sure that all modulefiles written in TCL start with the string #%Module
```

what `qt` version is `ecflow` supposed to depend on? has it changed with the initial `yum` commands?

**Comment by climbfuji** [comment]
It seems that you are missing all the steps in `configs/sites/noaa-aws/README.md`.

**Comment by climbfuji** [comment]
> It seems that you are missing all the steps in `configs/sites/noaa-aws/README.md`.

These are one-offs but need to be done. I believe @mark-a-potts did set up all of this already?

**Comment by mark-a-potts** [comment]
> 

I did work though the steps in the README.md file, but it looks like there were a couple of issues. First, the template for ecflow references a module for qt, which was not created. Maybe that section can just be removed from the ecflow modulefile since qt is installed as a system package? The second issue is that I didn't get everything copied over to the other machines quite right. I'll remove the reference to the qt module and make sure it gets copied correctly to the other machines.

**Comment by climbfuji** [comment]
@mark-a-potts Good point about the module file. On many HPCs we need that qt dependency in the ecflow modulefile, but of course not on Parallel Works where we install qt with yum in the system paths. So how about we just add a one-liner comment to the module file that says "if you need to load a qt module, this is the piece of code to use, otherwise remove from your modulefile"?

**Comment by ulmononian** [comment]
> @mark-a-potts Good point about the module file. On many HPCs we need that qt dependency in the ecflow modulefile, but of course not on Parallel Works where we install qt with yum in the system paths. So how about we just add a one-liner comment to the module file that says "if you need to load a qt module, this is the piece of code to use, otherwise remove from your modulefile"?

i would be on board with this. qt loading was the hiccup for me so this solves it.

**Comment by ulmononian** [comment]
thanks for following up on this @mark-a-potts!

**Comment by ulmononian** [comment]
i removed the qt reference in the ecflow module on aws and am running a quick test build of ufs-srw and ufs-wm envs there. i will approve once those installations pass.

**Review by ulmononian — APPROVED** [review]
built fine for me. g2g.

**Comment by ulmononian** [comment]
thanks for all the work on this @climbfuji. this effort really benefits epic and the wm future on the cloud!

**Comment by climbfuji** [comment]
@mark-a-potts I updated the modulefile template for `ecflow` based on your feedback. Please take another look. Thanks!

**Comment by mark-a-potts** [comment]
> @mark-a-potts I updated the modulefile template for `ecflow` based on your feedback. Please take another look. Thanks!

Looks good, but can you add "yum install -y m4" to the instructions in the README for basic_setup.sh? Even it if is already installed on some instances, it won't hurt to request it to be installed again, and the install for spack-stack won't work without it on our instances.

**Comment by climbfuji** [comment]
> > @mark-a-potts I updated the modulefile template for `ecflow` based on your feedback. Please take another look. Thanks!
> 
> Looks good, but can you add "yum install -y m4" to the instructions in the README for basic_setup.sh? Even it if is already installed on some instances, it won't hurt to request it to be installed again, and the install for spack-stack won't work without it on our instances.

Done!

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I included the spack submodule pointer update for your small MET PR (unset env variable) in this PR.

**Pull request merged**
