### PR TITLE
Update orion/hercules new installation directory

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
### Summary

Placed spack-stack-1.8.0 to the new directory.

### Testing

Installations successful.

### Applications affected

All using spack-stack-a.8.0 on Orion and/or Hercules.

### Systems affected

Orion and Hercules.

### Issue(s) addressed

Working toward #1156 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
Is this a duplicate of #1337?

**Comment by RatkoVasic-NOAA** [comment]
Yes, I didn't know other way :-)

**Review by climbfuji — COMMENTED** [review]
I think you should wait until the PR for release/1.8.0 is merged (as a squash merge), then cherry-pick that commit and create the PR for develop

**Comment by RatkoVasic-NOAA** [comment]
OK @climbfuji , then I will close this PR (to develop) and after PR to release/1.8.0 is merged I'll let @alex or you to do "cherry-pick". Or, you can show me steps to do that.

**Pull request closed without merging**
