### PR TITLE
Add util for checking installation permissions

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
### Summary

This PR adds a utility (with doco) for checking the permissions of installations, specifically to ensure that non-owning users/groups can access them.

### Testing

Tested the functionality/logic of the utility in CentOS 8 with some dummy files.

### Applications affected

No impact.

### Systems affected

No impact (except for helping identify permissions problems).

### Dependencies

n/a

### Issue(s) addressed

n/a

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji let me know what you think-- I don't know if the script is portable for Macs since I can't test, but I also don't know that there will ever be a situation where a Mac user needs to worry about permissions for other users.

**Comment by climbfuji** [comment]
This is a neat utility, however I think what would be even better (or a good additional step) is a simple check in `spack stack create env` if the umask will lead to an inaccessible install (e.g. `0077 = rwx------` or `0027 = rwxr-x---`)?

**Comment by AlexanderRichert-NOAA** [comment]
That sounds good-- I can think of some cases that would make it worth doing both (weird build systems; network FS quirks on Acorn). The one limitation I can think of is that creating and installing the environment could theoretically be done at two different times with different umasks... but short of creating our own install command, it couldn't hurt to have `spack stack create env` spit out a warning for a "bad" umask.

**Comment by climbfuji** [comment]
> That sounds good-- I can think of some cases that would make it worth doing both (weird build systems; network FS quirks on Acorn). The one limitation I can think of is that creating and installing the environment could theoretically be done at two different times with different umasks... but short of creating our own install command, it couldn't hurt to have `spack stack create env` spit out a warning for a "bad" umask.

I can take care of that part, thanks for the feedback.

**Review by climbfuji — COMMENTED** [review]
Do you want to add this step to the CI? We know that there should be no wrong permissions, but it would be good to run the script nonetheless?

**Comment by AlexanderRichert-NOAA** [comment]
Generally I think using this command will lead us to run chmod on our installations, as opposed to leading to "deep" changes to configs/recipes/codes. So for now I would say we don't need it in the CI, but we should revisit it if we run into issues that need a solution beyond just running chmod.

**Comment by climbfuji** [comment]
I would like to see the script being exercise = tested to not blow up, that's why I was asking. But it's ok as it is, too.

**Comment by AlexanderRichert-NOAA** [comment]
Ah I see what you mean. I think in a separate PR I'll add CI testing for utilities (including testing various cases for the duplicate checker).

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
