### PR TITLE
Build py-netcdf4/py-h5py without mpi; update mirror section of the docs

### PR DESCRIPTION
**Pull request by ulmononian**
Building py-netcdf4/py-h5py without mpi (i.e., ~mpi variant) seems to fix the hanging python script on compute nodes issue. tested w/ land DA letfk.py script on orion that failed with py-netcdf4/py-h5py +mpi, but now passes with changes.

this was installed here ` /work2/noaa/epic-ps/cbook/spack_work/spack-stack-1.2.0/envs/unified-env` and tested in land DA here `/work2/noaa/epic-ps/cbook/landDA/ue_pyfix`

also, updates the mirror section of the docs' maintainers chapter.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
This looks good to me.

I tested building the non-mpi versions of py-netcdf4 and py-hdf5 on my macOS without problem. The dependency on mpi4py is gone.

Can you please update the submodule pointer for spack to [425f8f2](https://github.com/NOAA-EMC/spack/commit/425f8f2dd8c00bcf21845ff225ceb256a6677fd7)?

Can you please update the submodule pioit

**Comment by ulmononian** [comment]
> This looks good to me.
> 
> I tested building the non-mpi versions of py-netcdf4 and py-hdf5 on my macOS without problem. The dependency on mpi4py is gone.
> 
> Can you please update the submodule pointer for spack to [425f8f2](https://github.com/NOAA-EMC/spack/commit/425f8f2dd8c00bcf21845ff225ceb256a6677fd7)?
> 
> Can you please update the submodule pioit

thanks for testing this. updated the spack submodule pointer to [425f8f2](https://github.com/NOAA-EMC/spack/commit/425f8f2dd8c00bcf21845ff225ceb256a6677fd7).

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
I enabled auto-merge. It should merge once the CI tests passed.

**Comment by ulmononian** [comment]
> I enabled auto-merge. It should merge once the CI tests passed.

how futuristic. thanks, @climbfuji!!!

**Pull request merged**
