### PR TITLE
Update compiler/MPI entries in site configs for the UE

### PR DESCRIPTION
**Pull request by ulmononian**
As @climbfuji mentioned in #478, the compiler and MPI entry formatting in the sites/packages.yaml files needs to be adjusted for the UE (to properly support both Intel-latest and GNU installs). Further, for sites on which the global-workflow is supported, Intel-18 is needed, so a few sites' (Jet, Hera, Orion, S4) packages.yaml and compilers.yaml files need to be updated to include proper paths to/info. about their respective Intel-18 installations.

I will start with these updates on the following sites: Jet, Hera, Cheyenne, Orion, and Gaea. Perhaps @climbfuji can comment as to what the plan is for installation and testing plan is on the Parallelworks clusters (Azure, AWS, GCP); if UE will be installed there, I can update those too. 

I do not have access to the remaining sites from https://spack-stack.readthedocs.io/en/latest/Platforms.html, so I can't check the compiler/MPI info there.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
This looks good to me. I'll update site configs that you do not have access to in a follow-up PR, possibly as part of the R2D2 MYSQL PR.

**Comment by ulmononian** [comment]
@climbfuji thanks for looking this over. i did not test any of this, but most of it was just re-arranging what was already present plus adding the intel 18 info (which i based on the core intel modules used in the respective global-workflow modules).

**Comment by climbfuji** [comment]
I think it would be good to test this as part of the R2D2 mysql PR, which requires updates to every site config. I am fine with merging your updates as they are, or pulling them into my PR.

**Comment by ulmononian** [comment]
@climbfuji feel free to merge them as is from this pr. i will follow up with your r2d2 updates.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
