### PR TITLE
Update esmf, fms, g2, g2tmpl and mapl versions

### LINKED ISSUE #1106: [INSTALL]: Add fms@2024.01 -> 2024.01.01 -> 2024.01.02 -> 2024.02 (in addition to or to replace current version in spack-stack-1.8.0)
### Package name

fms

### Package version/tag

2024.01 -> 2024.01.01 -> 2024.01.02 -> 2024.02 are small patch releases that we should use instead.

See https://github.com/NOAA-GFDL/FMS/releases/tag/2024.02

### Build options

Current

### Installation timeframe

For spack-stack-1.8.0.

### Other information

This version has a bug fix for linking the OpenMP-enabled version on macOS. It would be great to update to that version if possible.

### WCOSS2

- [X] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

Upgrade

### WCOSS2: Installation and testing

Current

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

### WCOSS2: Additional comments

_No response_

### LINKED ISSUE #1255: Update esmf, fms, g2, g2tmpl and mapl versions
**Is your feature request related to a problem? Please describe.**
Update esmf, fms, g2, g2tmpl and mapl versions 

**Describe the solution you'd like**
Use versions:
esmf@8.6.1
fms@2024.01
g2@3.5.1
g2tmpl@1.13.0
mapl@2.46.3

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
### Summary

Update default versions of esmf, fms, g2, g2tmpl and mapl packages.

### Testing

Tested previously with UFS-WM

### Applications affected

UFS WM

### Systems affected

All

### Dependencies

- [x] waiting on https://github.com/JCSDA/spack/pull/466

### Issue(s) addressed

Resolves #1255 
Resolves https://github.com/JCSDA/spack-stack/issues/1106

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by climbfuji** [comment]
We will need updates of esmf versions in a few other templates (skylab-dev, unified-dev, ...). I can push to your branch if you want. Are you sure you want fms@2024.01 and not the lates 2024.02? Doesn't seem to make sense to me to go with an older version.

**Comment by climbfuji** [comment]
we need to pull in Matt's mapl update PR from spack develop

**Comment by RatkoVasic-NOAA** [comment]
> We will need updates of esmf versions in a few other templates (skylab-dev, unified-dev, ...). I can push to your branch if you want. Are you sure you want fms@2024.01 and not the lates 2024.02? Doesn't seem to make sense to me to go with an older version.

I think skylab-dev and unified-dev have already correct versions.
As for fms, I was asked to test 2024.01 and that one passed WM tests. Not sure why they didn't ask for newer version.

**Comment by climbfuji** [comment]
I think we should use the latest available fms for spack-stack-1.8.0

**Comment by RatkoVasic-NOAA** [comment]
> I think we should use the latest available fms for spack-stack-1.8.0

I can do that, but we have to update spack as well, current one have latest fms@2024.01.01 
 in var/spack/repos/builtin/packages/fms/package.py

**Comment by climbfuji** [comment]
Let me take care of the spack updates (fms, mapl) - will be ready in 30mins or so

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA I took the liberty to push to your branch. This PR now depends on https://github.com/JCSDA/spack/pull/466

**Comment by RatkoVasic-NOAA** [comment]
I saw that, thanks.

**Comment by climbfuji** [comment]
I'll push the spack submodule ptr update and .gitmodules reversal after the current CI tests finished (last one is ubuntu gnu, currently doing mapl - close to finish).

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
@eap added you as reviewer FYI (several updates I am making to the jedi-ci specs)

**Pull request merged**
