### PR TITLE
Update FMS & SCOTCH defaults

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR updates default specs for fms and scotch in order to support UFS WM.

### CODE REVIEW

**Review by ulmononian — APPROVED** [review]
approving this now, but may revisit if it turns out that the `esmumps` variant is required...

**Review by climbfuji — APPROVED** [review]
Let's see what the CI tests are doing ...

**Comment by climbfuji** [comment]
Because I pushed my submodule pointer update a few seconds before you (https://github.com/JCSDA/spack-stack/pull/635), CI tests are running for that PR now.

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji I've updated to the current pointer, so would it make sense to cancel those and let these run since they'll need to anyway?

**Comment by climbfuji** [comment]
I've also updated the submodule pointers so same here ... we'll have to run them for both anyway.

**Pull request merged**
