### PR TITLE
Update of Derecho site config (Intel tested, GNU placeholder)

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

Another update to the Derecho site config to fix problems with previous installations, to include the latest Intel compiler, and to update the documentation. Note that GNU was added but not tested yet.

### Testing

Tested with the UFS weather model by @mark-a-potts (please provide details here if you want), with JEDI+FV3 and JEDI+MPAS (see https://github.com/JCSDA-internal/jedi-bundle/issues/63 and https://github.com/JCSDA-internal/mpas-bundle/issues/154 for remaining ctest failures)

### Applications affected

n/a

### Systems affected

New HPC Derecho

### Dependencies

n/a

### Issue(s) addressed

n/a (this is part of a JCSDA epic)

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [ ] ~~All dependency PRs/issues have been resolved and this PR can be merged.~~

### CODE REVIEW

**Review by ulmononian — APPROVED** [review]
thanks for testing w/ ufs-wm @mark-a-potts.

**Comment by mark-a-potts** [comment]
Everything is now working with my fork for derecho using the spack-stack-dev-20230825 environment. If we move that into the official unified-env environment, I can push that change into my PR for adding derecho to the WM as well.

**Comment by climbfuji** [comment]
> Everything is now working with my fork for derecho using the spack-stack-dev-20230825 environment. If we move that into the official unified-env environment, I can push that change into my PR for adding derecho to the WM as well.

Great!

Wondering if it makes sense to hold off with the UFS WM Derecho PR until we've installed spack-stack 1.5.0 (which we will start rolling out end of next week)?

Should we merge this spack-stack PR?

**Comment by mark-a-potts** [comment]
> > Everything is now working with my fork for derecho using the spack-stack-dev-20230825 environment. If we move that into the official unified-env environment, I can push that change into my PR for adding derecho to the WM as well.
> 
> Great!
> 
> Wondering if it makes sense to hold off with the UFS WM Derecho PR until we've installed spack-stack 1.5.0 (which we will start rolling out end of next week)?
> 
> Should we merge this spack-stack PR?

Yes, let's merge this. 

For the WM, I think I will go forward with it using spack-stack-1.4.1 since I think they want it for the SRW release as well, and you never know how long it is going to take to complete testing for 1.5.0.

**Comment by climbfuji** [comment]
Thanks for all your help with the testing, @mark-a-potts and @ulmononian

**Pull request merged**
