### PR TITLE
create env: warn if upstream environment's config doesn't match

### LINKED ISSUE #1092: create env: Warn if --upstream path's site & common don't match
As we're creating add on environments, there's always the possibility that the environment being chained to will have modifications to site/ and common/ not in the $SPACK_STACK_DIR/config/. `spack stack create env --upstream` should throw loud warnings if there are differences.

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
### Summary

This PR adds a warning to the `spack stack create env --upstream` command if the new environment newly populated site and common directories have configs that don't match those of the upstream. It uses `diff -rq`, so it should work on MacOS. This will mainly be useful on HPC systems where we've made local config updates, perhaps in specific envs, that didn't get looped back into develop.

### Testing

Testing on personal machine.

### Applications affected

n/a

### Systems affected

all

### Dependencies

none

### Issue(s) addressed

Fixes #1092

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Should we add this to the CI runs?

**Comment by AlexanderRichert-NOAA** [comment]
Yeah, I added some tests to confirm the new warnings are functioning. Meanwhile, all the workflows are failing... :upside_down_face:

**Comment by climbfuji** [comment]
must be a github glitch?

**Comment by climbfuji** [comment]
https://www.githubstatus.com/

**Comment by AlexanderRichert-NOAA** [comment]
(finally) got this working, so if @climbfuji @srherbener @RatkoVasic-NOAA can approve I'd love to get this merged without having to run the CI again :upside_down_face:

**Review by srherbener — APPROVED** [review]

**Pull request merged**
