### PR TITLE
Use external grep package in GitHub actions, new site config instructions, and pre-configured tier-1 sites

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

External grep in new site configs (documentation), CI, Containers, pre-configured sites (at least tier 1).

Tier 1 (mandatory):
- [ ] ~~acorn (EMC):~~ deferred to https://github.com/JCSDA/spack-stack/issues/1431
- [x] atlantis (@climbfuji)
- [x] aws-pcluster (JCSDA)
- [x] blueback (@climbfuji)
- [x] derecho (EPIC)
- [x] discover-scu16 (JCSDA)
- [x] discover-scu17 (JCSDA)
- [x] gaea-c5 (EPIC)
- [x] gaea-c6 (EPIC)
- [x] hera (EPIC)
- [x] hercules (EPIC)
- [x] jet (EPIC)
- [x] narwhal (@climbfuji)
- [x] nautilus (@climbfuji)
- [x] navy-aws (@climbfuji)
- [x] noaa-aws (EPIC)
- [x] noaa-azure (EPIC)
- [x] noaa-gcloud (EPIC)
- [x] orion (EPIC)
- [x] s4 (climbfuji)

Tier 2 (optional):
- [x] blackpearl(@climbfuji)
- [x] bounty (@climbfuji)
- [x] casper (@climbfuji)
- [ ] emc-rhel
- [ ] frontera
- [x] ~~linux.default~~ in documentation (secion "New Site Config")
- [x] ~~macos.default~~ in documentation (secion "New Site Config")

Container recipes:
- [x] GNU (@climbfuji)
- [x] Clang (@climbfuji)
- [x] Intel (@climbfuji)

CI:
- [x] All Linux runners (@climbfuji)
- [x] macOS runner (@climbfuji)

### Testing

See above

### Applications affected

None (external `grep` is a prerequisite for the upcoming GitHub CLI `gh` package).

### Systems affected

All.

### Dependencies

- [x] waiting on https://github.com/JCSDA/spack/pull/492

### Issue(s) addressed

Working towards #1105 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by rickgrubin-tomorrow** [comment]
EPIC hosts

- [x] derecho
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.1
```
- [x] gaea C5
```
$ which grep
/bin/grep
$ grep --version
grep (GNU grep) 3.1
```
- [x] gaea C6
```
$ which grep
/bin/grep
$ grep --version
grep (GNU grep) 3.1
```
- [x] hera
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.1
```
- [x] hercules
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.6
```
- [x] jet
```
$ which grep
/bin/grep

$ grep --version
grep (GNU grep) 3.1
```
- [x] noaa-aws
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.1
```
- [x] noaa-azure
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.1
```
- [x] noaa-gcloud
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.1
```
- [x] orion
```
$ which grep
/usr/bin/grep

$ grep --version
grep (GNU grep) 3.6
```

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Can you please provide details on the OS grep on Acorn so that we can merge this PR? Thanks.

**Comment by climbfuji** [comment]
This PR is blocking other PRs. Can someone please review? If we don't get the external grep info for acorn before merging, I will create an issue to remind us to add that missing site config update later. Thanks!

**Review by rickgrubin-noaa — APPROVED** [review]
LGTM

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Pull request merged**
