### PR TITLE
Update to new ReadTheDocs configuration

### LINKED ISSUE #691: Update ReadTheDocs configuration
**Is your feature request related to a problem? Please describe.**

ReadTheDocs is changing the way configuration is being done. The build engine at ReadTheDocs has been automatically providing default configuration (via a .readthedocs.yaml file), and they will stop doing this meaning that we have to specify a .readthedocs.yaml file in our project. The deadline for fixing this is Sep 25, 2023.

**Describe the solution you'd like**

Add a .readthedocs.yaml file to the project to satisfy the upcoming requirement from ReadTheDocs.

**Additional context**

Here are some references:

https://blog.readthedocs.com/migrate-configuration-v2/

https://docs.readthedocs.io/en/stable/examples.html

### PR DESCRIPTION
**Pull request by srherbener**
### Summary

This PR updates the ReadTheDocs configuration according to the ReadTheDocs upgrade request as described in: https://blog.readthedocs.com/migrate-configuration-v2/

### Testing

CI testing
- [x] Manual build test on readthdocs.org (SteveH)

### Applications affected

No impact on applications since this is just a documentation update.

### Systems affected

ReadTheDocs posting

### Dependencies

None

### Issue(s) addressed

Fixes #691 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications.
- [ ] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

**Comment by srherbener** [comment]
@AlexanderRichert-NOAA, @ulmononian do the CI tests run a ReadTheDocs build. If not, do you have suggestions on how to test this? Thanks!

**Review by ulmononian — APPROVED** [review]
thanks for doing this, @srherbener!

**Comment by AlexanderRichert-NOAA** [comment]
@srherbener if you go to readthedocs.org you can log in and add a project, point it to your repository (just point it to your PR branch), and build it.

**Comment by srherbener** [comment]
@AlexanderRichert-NOAA I have verified with a manual build at readthedocs.org that the new .readthedocs.yml file does indeed work. Thanks for the tip! (I actually found a fault in the YAML file and updated it to get it working)

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Pull request merged**
